theme: jekyll-theme-minimal
title: TFTP
description: An informational document about TFTP
show_downloads: false
logo: https://www.netscout.com/themes/custom/netscout/logo.svg
attribution: maintained by <a href="//netscout.com">Netscout</a> with â¤ï¸.
disclaimer: TFTP is an open standard, with which Netscout has no affiliation. This page is maintained as a courtesy ğŸ˜Š.